# Generated by Django 4.0.5 on 2022-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('logo', models.ImageField(upload_to='static/img/')),
                ('bgimage', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
