# Generated by Django 4.0.5 on 2022-09-27 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('startPrice', models.BigIntegerField(null=True)),
                ('endPrice', models.BigIntegerField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('logo', models.ImageField(upload_to='static/img/')),
                ('bgimage', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('district', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='sahayatriapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('inclusions', models.TextField(null=True)),
                ('exclusions', models.TextField(null=True)),
                ('mapurl', models.URLField(null=True)),
                ('days', models.IntegerField(default=1, null=True)),
                ('nights', models.IntegerField(null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('Itnerary', models.TextField(null=True)),
                ('entrydate', models.DateTimeField(auto_now_add=True, null=True)),
                ('valid_date', models.DateTimeField(null=True)),
                ('offers', models.CharField(default='N/A', max_length=250, null=True)),
                ('overview', models.TextField(null=True)),
                ('image1', models.ImageField(null=True, upload_to='media')),
                ('image2', models.ImageField(null=True, upload_to='media')),
                ('image3', models.ImageField(null=True, upload_to='media')),
                ('image4', models.ImageField(null=True, upload_to='media')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bud', to='sahayatriapp.budgetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext1', models.CharField(max_length=100, null=True)),
                ('alttext2', models.CharField(max_length=100, null=True)),
                ('alttext3', models.CharField(max_length=100, null=True)),
                ('sliderimg', models.ImageField(upload_to='static/img/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_rate', to='sahayatriapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='sahayatriapp.typecategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district0', to='sahayatriapp.district'),
        ),
        migrations.AddField(
            model_name='product',
            name='muni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muni0', to='sahayatriapp.municipality'),
        ),
        migrations.AddField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prov0', to='sahayatriapp.province'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('type_of_user', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.CharField(default='Nepal', max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('pan_no', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_website', models.URLField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district2', to='sahayatriapp.district')),
                ('muni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muni2', to='sahayatriapp.municipality')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prov2', to='sahayatriapp.province')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itnerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Day 1', max_length=250, null=True)),
                ('detail', models.TextField(null=True)),
                ('travel', models.TextField(null=True)),
                ('breakfast', models.TextField(null=True)),
                ('lunch', models.TextField(null=True)),
                ('dinner', models.TextField(null=True)),
                ('accomodation', models.TextField(null=True)),
                ('sighting', models.TextField(null=True)),
                ('extra', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.merchant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itner', to='sahayatriapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(upload_to='media')),
                ('image3', models.ImageField(upload_to='media')),
                ('image4', models.ImageField(upload_to='media')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.merchant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='sahayatriapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='sahayatriapp.province'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_of_user', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(default='Nepal', max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district1', to='sahayatriapp.district')),
                ('muni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muni1', to='sahayatriapp.municipality')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prov1', to='sahayatriapp.province')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bucketlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
