# Generated by Django 4.0.5 on 2022-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altext', models.CharField(max_length=100, null=True)),
                ('sliderimg', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
