# Generated by Django 4.0.5 on 2022-09-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refId',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
