# Generated by Django 4.0 on 2022-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0002_order_bucketlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refId',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
