# Generated by Django 4.0.5 on 2022-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0002_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='altext',
            new_name='alttext1',
        ),
        migrations.AddField(
            model_name='slider',
            name='alttext2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='alttext3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
