# Generated by Django 4.0 on 2022-09-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0003_order_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='posted_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
