# Generated by Django 4.0 on 2022-06-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0004_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('MERCHANT', 'Merchant')], max_length=50, null=True, verbose_name='Type')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.user'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.user'),
        ),
    ]
