# Generated by Django 4.0 on 2022-06-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0003_rename_altext_slider_alttext1_slider_alttext2_and_more'),
        ('sahayatriapp', '0007_alter_customer_user_alter_merchant_user_delete_user'),
    ]

    operations = [
    ]
