# Generated by Django 4.0 on 2022-06-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0008_merge_20220606_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='posted_by',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
