# Generated by Django 4.0.5 on 2022-07-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0011_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.TextField(null=True)),
                ('travelinfo', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.merchant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='sahayatriapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Itnerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Day 1', max_length=250, null=True)),
                ('detail', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahayatriapp.merchant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itner', to='sahayatriapp.product')),
            ],
        ),
    ]
