# Generated by Django 4.0.5 on 2022-07-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0012_customer_status_merchant_status_product_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('startPrice', models.BigIntegerField(null=True)),
                ('endPrice', models.BigIntegerField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
