# Generated by Django 4.0.5 on 2022-07-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0013_budgetcategory_typecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='static/img/')),
                ('image2', models.ImageField(upload_to='static/img/')),
                ('image3', models.ImageField(upload_to='static/img/')),
                ('image4', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
