# Generated by Django 4.0.5 on 2022-08-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0017_alter_typecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itnerary',
            name='accomodation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnerary',
            name='breakfast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnerary',
            name='dinner',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnerary',
            name='lunch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnerary',
            name='sighting',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnerary',
            name='travel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='exclusions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inclusions',
            field=models.TextField(null=True),
        ),
    ]
