# Generated by Django 4.0.5 on 2022-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0018_itnerary_accomodation_itnerary_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itnerary',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
