# Generated by Django 4.0.5 on 2022-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0020_product_mapurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nights',
            field=models.IntegerField(null=True),
        ),
    ]
