# Generated by Django 4.0.5 on 2022-09-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0023_remove_municipality_province_alter_district_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Itnerary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='newprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
