# Generated by Django 4.0.5 on 2022-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0027_alter_product_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Overview',
        ),
    ]
