# Generated by Django 4.0.5 on 2022-09-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0029_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
