# Generated by Django 4.0.5 on 2022-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0034_product_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='posted_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='posted_by',
            field=models.IntegerField(null=True),
        ),
    ]
