# Generated by Django 4.0.5 on 2022-09-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0035_bucketlist_posted_by_order_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='company_website',
            field=models.URLField(null=True),
        ),
    ]
