# Generated by Django 4.0.5 on 2022-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayatriapp', '0036_alter_merchant_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
